### ISSUE TITLE
这个判断过于严格了

### ISSUE THREAD

**Issue by zhuweiyou** [dj940212/hongbao-bot#1]
https://github.com/dj940212/hongbao-bot/blob/08bff38331474366acaa84de4e9882709ea15a94/utils.js#L28

现在我都放宽了判断，除了 `activity.waimai` 还可能有 `activity-sh.waimai` 上海这样的子域

**Comment by dj940212** [comment]
@zhuweiyou 这种我还遇到过，我去修改一下
