### ISSUE TITLE
npm install 依赖太慢了

### ISSUE THREAD

**Issue by ontheway1215** [dj940212/hongbao-bot#6]
依赖并不多，但是为什么特别慢，十几分钟还没安装完成
![image](https://user-images.githubusercontent.com/11936847/36826687-1c354cac-1d4a-11e8-941b-f94c0d77d815.png)

**Comment by dj940212** [comment]
因为有墙啊，你可以试试淘宝镜像
```
npm install cnpm -g
cnpm install
```

**Comment by ontheway1215** [comment]
已解决，谢谢。

**Comment by beelzebubxbh** [comment]
为什么不使用墙外主机
