### ISSUE TITLE
在服务器上运行app时无法启动chrome

### ISSUE THREAD

**Issue by ontheway1215** [dj940212/hongbao-bot#7]
楼主是部署在服务器上的么？
在服务器上部署时出现错误
![image](https://user-images.githubusercontent.com/11936847/36841273-c71787ba-1d82-11e8-96fa-876d00e3b4cc.png)

**Comment by emtry** [comment]
同样问题
Debian

**Comment by dj940212** [comment]
都是linux环境安装puppeteer缺少文件导致，google一下应该有解决方案

**Comment by emtry** [comment]
@dj940212 解决了，安装了好多依赖
